// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADHj3QAZYsViw9zAE-uAnDN45A66i7i9U',
    appId: '1:97951007463:web:4e08405668a76372d79842',
    messagingSenderId: '97951007463',
    projectId: 'basku-bn',
    authDomain: 'basku-bn.firebaseapp.com',
    databaseURL: 'https://basku-bn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basku-bn.firebasestorage.app',
    measurementId: 'G-7MCDXRGK38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6MtlfgBJ22B5zjEVs1QJ5u1yd2u6_a1s',
    appId: '1:97951007463:android:5eb30b037e895dbbd79842',
    messagingSenderId: '97951007463',
    projectId: 'basku-bn',
    databaseURL: 'https://basku-bn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basku-bn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSmxn6J7ZU4_ro0w7LhHUOyJCXbV9fOus',
    appId: '1:97951007463:ios:65418ce4350059d3d79842',
    messagingSenderId: '97951007463',
    projectId: 'basku-bn',
    databaseURL: 'https://basku-bn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basku-bn.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSmxn6J7ZU4_ro0w7LhHUOyJCXbV9fOus',
    appId: '1:97951007463:ios:65418ce4350059d3d79842',
    messagingSenderId: '97951007463',
    projectId: 'basku-bn',
    databaseURL: 'https://basku-bn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basku-bn.firebasestorage.app',
    iosBundleId: 'com.example.busApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADHj3QAZYsViw9zAE-uAnDN45A66i7i9U',
    appId: '1:97951007463:web:dd5d551ce21c8e9ed79842',
    messagingSenderId: '97951007463',
    projectId: 'basku-bn',
    authDomain: 'basku-bn.firebaseapp.com',
    databaseURL: 'https://basku-bn-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'basku-bn.firebasestorage.app',
    measurementId: 'G-VNN7XMWG5P',
  );

}