name: bus_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  photo_view: ^0.15.0


  # Cupertino icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0

  # Geolocation and mapping
  geolocator: ^14.0.2
  flutter_map: ^8.2.1
  latlong2: ^0.9.1

  # State management
  provider: ^6.1.5+1

  # Localization
  flutter_localizations:
    sdk: flutter

  # Connectivity
  connectivity_plus: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
  - lib/l10n/
  - assets/offline_map.png
  - assets/logoAsset.png
